#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 5.0.3
#  in conjunction with Tcl version 8.6
#    Mar 16, 2020 03:03:41 PM IST  platform: Linux

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import ani_support
import os.path

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    global prog_location
    prog_call = sys.argv[0]
    prog_location = os.path.split(prog_call)[0]
    root = tk.Tk()
    top = Toplevel1 (root)
    ani_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_Toplevel1(root, *args, **kwargs)' .'''
    global w, w_win, root
    global prog_location
    prog_call = sys.argv[0]
    prog_location = os.path.split(prog_call)[0]
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    ani_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        font14 = "-family {Manjari} -size 14"
        ''' Initializing Tkinter variables '''
        self.name = tk.StringVar()
        self.rating = tk.StringVar()
        
        
        top.geometry("464x588+383+105")
        top.minsize(1, 1)
        top.maxsize(1351, 738)
        top.resizable(0, 0)
        top.title("AniBook")
        top.configure(background="#566cd8")
        top.configure(highlightcolor="black")


        self.Label1 = tk.Label(top)
        self.Label1.place(relx=0.129, rely=0.044, height=204, width=342)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(cursor="heart")
        photo_location = os.path.join(prog_location,"./Source/bg1.png")
        global _img0
        _img0 = tk.PhotoImage(file=photo_location)
        self.Label1.configure(image=_img0)
        self.Label1.configure(text='''Label''')

        self.Frame1 = tk.Frame(top)
        self.Frame1.place(relx=0.022, rely=0.476, relheight=0.502
                , relwidth=0.938)
        self.Frame1.configure(relief='groove')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief="groove")
        self.Frame1.configure(background="#6680d8")

        self.Entry1 = tk.Entry(self.Frame1,textvariable=self.name)
        self.Entry1.place(relx=0.437, rely=0.068,height=23, relwidth=0.52)
        self.Entry1.configure(background="white")
        self.Entry1.configure(font="-family {Droid Sans Fallback} -size 11")
        self.Entry1.configure(selectbackground="#c4c4c4")

        self.Label3 = tk.Label(self.Frame1)
        self.Label3.place(relx=0.023, rely=0.034, height=25, width=99)
        self.Label3.configure(activebackground="#f9f9f9")
        self.Label3.configure(background="#6680d8")
        self.Label3.configure(font="-family {Noto Sans CJK HK} -size 13 -underline 1")
        self.Label3.configure(text='''Anime''')

        self.Label3_1 = tk.Label(self.Frame1)
        self.Label3_1.place(relx=0.023, rely=0.169, height=25, width=99)
        self.Label3_1.configure(activebackground="#f9f9f9")
        self.Label3_1.configure(background="#6680d8")
        self.Label3_1.configure(font="-family {Noto Sans CJK HK} -size 13 -underline 1")
        self.Label3_1.configure(text='''Ratings''')

        self.Entry1_2 = tk.Entry(self.Frame1,textvariable=self.rating)
        self.Entry1_2.place(relx=0.437, rely=0.203,height=23, relwidth=0.106)
        self.Entry1_2.configure(background="white")
        self.Entry1_2.configure(font="-family {KacstArt} -size 11")
        self.Entry1_2.configure(selectbackground="#c4c4c4")

        self.Label3_2 = tk.Label(self.Frame1)
        self.Label3_2.place(relx=0.023, rely=0.339, height=25, width=99)
        self.Label3_2.configure(activebackground="#f9f9f9")
        self.Label3_2.configure(background="#6680d8")
        self.Label3_2.configure(font="-family {Noto Sans CJK HK} -size 13 -underline 1")
        self.Label3_2.configure(text='''Review''')

        self.Text1 = tk.Text(self.Frame1)
        self.Text1.place(relx=0.437, rely=0.339, relheight=0.322, relwidth=0.52)
        self.Text1.configure(background="white")
        self.Text1.configure(font="-family {DejaVu Sans Mono} -size 11")
        self.Text1.configure(maxundo="5")
        self.Text1.configure(selectbackground="#c4c4c4")
        self.Text1.configure(wrap="word")

        self.Button1 = tk.Button(self.Frame1)
        self.Button1.place(relx=0.184, rely=0.746, height=35, width=111)
        self.Button1.configure(activebackground="#6680d8")
        self.Button1.configure(background="#828dd8")
        self.Button1.configure(borderwidth="3")
        self.Button1.configure(command=ani_support.getit)
        self.Button1.configure(font=font14)
        self.Button1.configure(foreground="#ffffff")
        self.Button1.configure(text='''Get''')

        self.Button1_1 = tk.Button(self.Frame1)
        self.Button1_1.place(relx=0.552, rely=0.746, height=35, width=111)
        self.Button1_1.configure(activebackground="#6680d8")
        self.Button1_1.configure(background="#828dd8")
        self.Button1_1.configure(borderwidth="3")
        self.Button1_1.configure(command=lambda :ani_support.save(self.name.get(),self.rating.get(),self.Text1.get(1.0,tk.END)))
        self.Button1_1.configure(font="-family {Manjari} -size 14")
        self.Button1_1.configure(foreground="#ffffff")
        self.Button1_1.configure(text='''Save''')

        self.Label2 = tk.Label(top)
        self.Label2.place(relx=0.345, rely=0.408, height=31, width=139)
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(background="#566cd8")
        self.Label2.configure(font="-family {URW Gothic L} -size 17 -weight bold")
        self.Label2.configure(foreground="#8ed67c")
        self.Label2.configure(text='''AniBook''')

if __name__ == '__main__':
    vp_start_gui()





