#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 5.0.3
#  in conjunction with Tcl version 8.6
#    Mar 16, 2020 02:41:05 PM IST  platform: Linux
#    Mar 16, 2020 03:03:29 PM IST  platform: Linux
import sqlite3
import sys
import datetime
import pandas as pd

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def run():
    print('ani_support.run')
    sys.stdout.flush()

def getit():
    connect = sqlite3.connect('anibook.db')
    query = ''' SELECT * FROM book ''' 
    try:
        df = pd.read_sql(query,connect)
    except :
        print('No Table founded')
    else:
        df.to_csv('AniBook.csv',index=False)
        print('File Saved !')
    
def save(anime,ratings,review):
    connect = sqlite3.connect('anibook.db')
    cursorobj = connect.cursor()
    try:
        createtable = ''' CREATE TABLE book(
        id INT PRIMARY KEY,
        anime varchar(40) NOT NULL UNIQUE,
        ratings DECIMAL(3,2) NOT NULL,
        review VARCHAR(50) DEFAULT 'no review',
        day DATE NOT NULL
        );'''
        cursorobj.execute(createtable)
    except :
        pass
    cursorobj.execute('''SELECT * FROM book''')

    command = ''' INSERT INTO book(id,anime,ratings,review,day) VALUES({},'{}',{},'{}','{}'); '''.format(len(cursorobj.fetchall())+1,anime,float(ratings),review.rstrip(),datetime.datetime.now().strftime('%Y-%m-%d')) 
    
    cursorobj.execute(command)
    connect.commit()
    connect.close()
    print('Saved !')
def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import ani
    ani.vp_start_gui()





